version: "3"
services:
  # my-proapp:
  #   image: ${docker-registry}/my-proapp:1.0
  #   ports:
  #    - 3000:3000 
  mongodb:
    image: mongo:4.4
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db
      #different databases will have different data paths eg for mysql is /var/lib/mysql/data
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
volumes:
  mongo-data:
     driver: local
  
  #mongo data will persist in mongo-data volume